-- MySQL Script generated by MySQL Workbench
-- 09/07/16 21:35:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Consejero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consejero` (
  `id_Consejero` VARCHAR(10) NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL DEFAULT 'Sin Nombre' COMMENT '',
  PRIMARY KEY (`id_Consejero`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `id_Estudiante` VARCHAR(15) NOT NULL DEFAULT 'Sin ID' COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL DEFAULT 'Sin Nombre' COMMENT '',
  `Apellido_paterno` VARCHAR(45) NOT NULL DEFAULT 'Sin Apellido P' COMMENT '',
  `Apellido Materno` VARCHAR(45) NOT NULL DEFAULT 'Sin Apellido M' COMMENT '',
  `fecha_nac` DATE NOT NULL COMMENT '',
  `Telefono` VARCHAR(25) NULL COMMENT '',
  `id_consejero` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`id_Estudiante`)  COMMENT '',
  CONSTRAINT `id_consejero`
    FOREIGN KEY (`id_consejero`)
    REFERENCES `mydb`.`Consejero` (`id_Consejero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_consejero_idx` ON `mydb`.`Estudiante` (`id_consejero` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`C_tipo_de_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`C_tipo_de_personal` (
  `id_tipo` INT NOT NULL DEFAULT 0 COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL DEFAULT 'Sin descripcion' COMMENT '',
  PRIMARY KEY (`id_tipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Moderador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Moderador` (
  `id_Moderador` VARCHAR(10) NOT NULL DEFAULT 'Sin ID' COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL COMMENT '',
  `id_tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_Moderador`)  COMMENT '',
  CONSTRAINT `id_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `mydb`.`C_tipo_de_personal` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_tipo_idx` ON `mydb`.`Moderador` (`id_tipo` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`Clubes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clubes` (
  `id_Clubes` VARCHAR(20) NOT NULL DEFAULT 'Sin ID' COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL COMMENT '',
  `Moderador_id_Moderador` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`id_Clubes`)  COMMENT '',
  CONSTRAINT `fk_Clubes_Moderador1`
    FOREIGN KEY (`Moderador_id_Moderador`)
    REFERENCES `mydb`.`Moderador` (`id_Moderador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Clubes_Moderador1_idx` ON `mydb`.`Clubes` (`Moderador_id_Moderador` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `id_Actividad` VARCHAR(10) NOT NULL DEFAULT 'Sin ID' COMMENT '',
  `Descripcion` VARCHAR(100) NOT NULL DEFAULT 'Sin descripcion' COMMENT '',
  `fecha_actividad` DATE NOT NULL COMMENT '',
  `id_club` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id_Actividad`)  COMMENT '',
  CONSTRAINT `id_club`
    FOREIGN KEY (`id_club`)
    REFERENCES `mydb`.`Clubes` (`id_Clubes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_club_idx` ON `mydb`.`Actividad` (`id_club` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante_has_Clubes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante_has_Clubes` (
  `Estudiante_id_Estudiante` VARCHAR(15) NOT NULL COMMENT '',
  `Clubes_id_Clubes` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`Estudiante_id_Estudiante`, `Clubes_id_Clubes`)  COMMENT '',
  CONSTRAINT `fk_Estudiante_has_Clubes_Estudiante1`
    FOREIGN KEY (`Estudiante_id_Estudiante`)
    REFERENCES `mydb`.`Estudiante` (`id_Estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Clubes_Clubes1`
    FOREIGN KEY (`Clubes_id_Clubes`)
    REFERENCES `mydb`.`Clubes` (`id_Clubes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estudiante_has_Clubes_Clubes1_idx` ON `mydb`.`Estudiante_has_Clubes` (`Clubes_id_Clubes` ASC)  COMMENT '';

CREATE INDEX `fk_Estudiante_has_Clubes_Estudiante1_idx` ON `mydb`.`Estudiante_has_Clubes` (`Estudiante_id_Estudiante` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
