-- MySQL Script generated by MySQL Workbench
-- 08/22/16 19:43:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `id_paciente` VARCHAR(10) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'Sin nombre' COMMENT '',
  `apellidos` VARCHAR(45) NOT NULL DEFAULT 'Sin apellidos' COMMENT '',
  `direccion` VARCHAR(45) NOT NULL DEFAULT 'Sin direccion' COMMENT '',
  `poblacion` VARCHAR(45) NULL DEFAULT 'Sin poblacion' COMMENT '',
  `provincia` VARCHAR(45) NULL DEFAULT 'Sin provincia' COMMENT '',
  `CP` VARCHAR(10) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL DEFAULT 'Sin telefono' COMMENT '',
  `fecha_nacimiento` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id_paciente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `id_medico` VARCHAR(10) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'Sin nombre' COMMENT '',
  `apellidos` VARCHAR(45) NOT NULL DEFAULT 'Sin apellidos' COMMENT '',
  `telefono` VARCHAR(45) NULL DEFAULT 'Sin telefono' COMMENT '',
  `especialidad` VARCHAR(45) NOT NULL DEFAULT 'Sin especialidad' COMMENT '',
  PRIMARY KEY (`id_medico`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingreso` (
  `id_ingreso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha_ingreso` DATE NOT NULL COMMENT '',
  `habitacion` VARCHAR(45) NOT NULL COMMENT '',
  `cama` VARCHAR(45) NOT NULL COMMENT '',
  `paciente_id_paciente` VARCHAR(10) NOT NULL COMMENT '',
  `medico_id_medico` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`id_ingreso`, `paciente_id_paciente`, `medico_id_medico`)  COMMENT '',
  CONSTRAINT `fk_ingreso_paciente`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `mydb`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_medico1`
    FOREIGN KEY (`medico_id_medico`)
    REFERENCES `mydb`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ingreso_paciente_idx` ON `mydb`.`ingreso` (`paciente_id_paciente` ASC)  COMMENT '';

CREATE INDEX `fk_ingreso_medico1_idx` ON `mydb`.`ingreso` (`medico_id_medico` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
