-- MySQL Script generated by MySQL Workbench
-- 08/22/16 21:08:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `RFC` VARCHAR(15) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'Sin nombre' COMMENT '',
  `direccion` VARCHAR(45) NOT NULL DEFAULT 'Sin direccion' COMMENT '',
  `telefono` VARCHAR(25) NULL COMMENT '',
  `pagina_web` VARCHAR(60) NULL DEFAULT 'Sin pagina web' COMMENT '',
  PRIMARY KEY (`RFC`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `RFC` VARCHAR(15) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'Sin nombre' COMMENT '',
  `calle` VARCHAR(45) NULL DEFAULT 'Sin calle' COMMENT '',
  `colonia` VARCHAR(45) NULL DEFAULT 'Sin colonia' COMMENT '',
  `ciudad` VARCHAR(45) NULL DEFAULT 'Sin ciudad' COMMENT '',
  `numero` VARCHAR(45) NULL DEFAULT 'Sin numero' COMMENT '',
  PRIMARY KEY (`RFC`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` VARCHAR(10) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'Sin nombre' COMMENT '',
  `descripcion` VARCHAR(100) NULL DEFAULT 'Sin descripcion' COMMENT '',
  PRIMARY KEY (`id_categoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id_productos` VARCHAR(10) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'sin nombre' COMMENT '',
  `precio` FLOAT NOT NULL COMMENT '',
  `existencia` INT NOT NULL COMMENT '',
  `id_categoria` VARCHAR(10) NOT NULL COMMENT '',
  `id_provedoor` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id_productos`)  COMMENT '',
  CONSTRAINT `producto_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proveedor_producto`
    FOREIGN KEY (`id_provedoor`)
    REFERENCES `mydb`.`proveedor` (`RFC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `producto_categoria_idx` ON `mydb`.`productos` (`id_categoria` ASC)  COMMENT '';

CREATE INDEX `proveedor_producto_idx` ON `mydb`.`productos` (`id_provedoor` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `id_venta` VARCHAR(15) NOT NULL COMMENT '',
  `descuento` FLOAT NOT NULL COMMENT '',
  `fecha_venta` DATE NOT NULL COMMENT '',
  `id_cliente` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id_venta`)  COMMENT '',
  CONSTRAINT `cliente_venta`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`RFC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cliente_venta_idx` ON `mydb`.`venta` (`id_cliente` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_venta` (
  `id_disc` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_venta` VARCHAR(15) NOT NULL COMMENT '',
  `precio_momento` FLOAT NOT NULL COMMENT '',
  `cantidad_vendida` VARCHAR(45) NOT NULL COMMENT '',
  `id_producto` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`id_disc`, `id_venta`)  COMMENT '',
  CONSTRAINT `Venta_detalleventa`
    FOREIGN KEY (`id_venta`)
    REFERENCES `mydb`.`venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_detalle`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`productos` (`id_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Venta_detalleventa_idx` ON `mydb`.`detalle_venta` (`id_venta` ASC)  COMMENT '';

CREATE INDEX `producto_detalle_idx` ON `mydb`.`detalle_venta` (`id_producto` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`telefonos_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefonos_cliente` (
  `disc` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `telefono` VARCHAR(15) NOT NULL COMMENT '',
  `rfc_cliente` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`disc`, `rfc_cliente`)  COMMENT '',
  CONSTRAINT `telefono_cliente`
    FOREIGN KEY (`rfc_cliente`)
    REFERENCES `mydb`.`cliente` (`RFC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `telefono_cliente_idx` ON `mydb`.`telefonos_cliente` (`rfc_cliente` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
